# Generated by Django 5.2.7 on 2025-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero')], default='CAJERO', max_length=20),
        ),
    ]
