# Generated by Django 5.2.7 on 2025-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='mp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
