# Generated by Django 5.2.6 on 2025-10-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='p_inventario',
            new_name='Inventario',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
