# Generated by Django 5.2.7 on 2025-11-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
