# Generated by Django 5.2.7 on 2025-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
