# Generated by Django 5.2.7 on 2025-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_cambio_venta_metodo_pago_venta_monto_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
