# Generated by Django 5.2.7 on 2025-11-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_venta_descuento_general_venta_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
