# Generated by Django 5.2.7 on 2025-11-19 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_venta_usuario_delete_detalleventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
