# Generated by Django 5.2.7 on 2025-11-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_total_and_more'),
        ('inventario', '0010_alter_ordencompra_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='producto_codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
    ]
